### Training a Random Forest Regressor model
Training a random forest regressor that predicts FPL points for the upcoming GW for players. This is a general model, and uses position as one of the predictors. A future step might be to produce a separate model for each position so that position-specific features can be better considered.

Rolling game statistics are key to the model - they will be computed on the previous three games for each player, and used as predictor features.

In [1]:
import os
import torch
import pandas as pd
import numpy as np
from model import AdvancedLSTM
import pickle
from eval import get_season_performance, season_performance_with_unlimited_transfers

In [2]:
base_path = os.getcwd()
base_path

'/Users/bragehs/Documents/FPL_forecast/predictor'

In [3]:
data_path = os.path.join(base_path, 'processed_data')
data_path

'/Users/bragehs/Documents/FPL_forecast/predictor/processed_data'

In [4]:
X_train = torch.load(data_path + '/X_train.pt', weights_only=True)
y_train = torch.load(data_path + '/y_train.pt', weights_only=True)
train_mapping = pd.read_csv(data_path + '/train_mapping.csv')

X_val = torch.load(data_path + '/X_val.pt', weights_only=True)
y_val = torch.load(data_path + '/y_val.pt', weights_only=True)

X_test = torch.load(data_path + '/X_test.pt', weights_only=True)
y_test = torch.load(data_path + '/y_test.pt', weights_only=True)
test_mapping = pd.read_csv(data_path + '/test_mapping.csv')

In [5]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_val shape: {X_val.shape}")
print(f"y_val shape: {y_val.shape}")

X_train shape: torch.Size([169711, 5, 50])
y_train shape: torch.Size([169711, 1])
X_val shape: torch.Size([11384, 5, 50])
y_val shape: torch.Size([11384, 1])

In [6]:
# Find all test_mapping rows for Mohamed Salah
salah_mapping = test_mapping[test_mapping['name'] == 'mohamed_salah']

# Get the sequence indices for Salah
salah_sequence_indices = salah_mapping['sequence_idx'].values

# Extract the corresponding X_test data for Salah
salah_x_test = X_test[salah_sequence_indices]

# You can also get the corresponding y_test data
salah_y_test = y_test[salah_sequence_indices]

In [7]:
last_1_assists_idx = 2
last_1_goals_scored_idx = 8

In [8]:
#sanity check to see there is no data leakage
for i in range(salah_x_test.shape[0]):
    last_1_assists = salah_x_test[i, -1, last_1_assists_idx]
    last_1_goals_scored = salah_x_test[i, -1,  last_1_goals_scored_idx]
    
    print(f"Gameweek {i + 1}: Last 1 Assists: {last_1_assists}, Last 1 Goals Scored: {last_1_goals_scored}, Total Points: {salah_y_test[i]}")

Gameweek 1: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.0, Total Points: tensor([14.])
Gameweek 2: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.42458099126815796, Total Points: tensor([10.])
Gameweek 3: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.27094972133636475, Total Points: tensor([17.])
Gameweek 4: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.44972068071365356, Total Points: tensor([2.])
Gameweek 5: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.23184357583522797, Total Points: tensor([6.])
Gameweek 6: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.5586591958999634, Total Points: tensor([10.])
Gameweek 7: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.35474860668182373, Total Points: tensor([3.])
Gameweek 8: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.11731843650341034, Total Points: tensor([12.])
Gameweek 9: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.3212290406227112, Total Points: tensor([10.])
Gameweek 10: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.2821229100227356, Total Points: tensor([9.])
Gameweek 11: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.3072625696659088, Total Points: tensor([14.])
Gameweek 12: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.37150838971138, Total Points: tensor([13.])
Gameweek 13: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.5083798766136169, Total Points: tensor([13.])
Gameweek 14: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.2821229100227356, Total Points: tensor([18.])
Gameweek 15: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.5698323845863342, Total Points: tensor([13.])
Gameweek 16: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.3687150776386261, Total Points: tensor([5.])
Gameweek 17: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.20391061902046204, Total Points: tensor([21.])
Gameweek 18: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.7039105892181396, Total Points: tensor([9.])
Gameweek 19: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.5167597532272339, Total Points: tensor([16.])
Gameweek 20: Last 1 Assists: 0.5, Last 1 Goals Scored: 0.6899441480636597, Total Points: tensor([7.])
Gameweek 21: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.287709504365921, Total Points: tensor([2.])
Gameweek 22: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.29050278663635254, Total Points: tensor([3.])
Gameweek 23: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.4189944267272949, Total Points: tensor([8.])
Gameweek 24: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.35754188895225525, Total Points: tensor([16.])
Gameweek 25: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.46927374601364136, Total Points: tensor([8.])
Gameweek 26: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.21229049563407898, Total Points: tensor([14.])
Gameweek 27: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.4078212380409241, Total Points: tensor([6.])
Gameweek 28: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.33519554138183594, Total Points: tensor([15.])
Gameweek 29: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.6145251393318176, Total Points: tensor([12.])
Gameweek 30: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.3212290406227112, Total Points: tensor([3.])
Gameweek 31: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.17877094447612762, Total Points: tensor([2.])
Gameweek 32: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.1284916251897812, Total Points: tensor([6.])
Gameweek 33: Last 1 Assists: 0.25, Last 1 Goals Scored: 0.20391061902046204, Total Points: tensor([3.])
Gameweek 34: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.24301676452159882, Total Points: tensor([8.])
Gameweek 35: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.4078212380409241, Total Points: tensor([2.])
Gameweek 36: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.13966479897499084, Total Points: tensor([2.])
Gameweek 37: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.1508379876613617, Total Points: tensor([2.])
Gameweek 38: Last 1 Assists: 0.0, Last 1 Goals Scored: 0.2821229100227356, Total Points: tensor([10.])

In [9]:
best_model_data = torch.load("best_model.pth", map_location=torch.device('cpu'))

/var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/ipykernel_12080/2890380057.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  best_model_data = torch.load("best_model.pth", map_location=torch.device('cpu'))

In [10]:
print(best_model_data['hidden_dim'])
print(best_model_data['num_layers'])
print(best_model_data['num_fc_layers'])

192
3
3

In [11]:
model = AdvancedLSTM(
    hidden_dim=best_model_data['hidden_dim'],
    num_layers=best_model_data['num_layers'],
    input_dim= best_model_data['input_dim'],
    output_dim=1,
    num_fc_layers=best_model_data['num_fc_layers'],
) 
model.load_state_dict(best_model_data['model_state_dict'])

In [12]:
#print number of parameters in the model
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Number of parameters in the model: {num_params}")

Number of parameters in the model: 803809

In [13]:
model.eval()

AdvancedLSTM(
  (lstm): LSTM(50, 192, num_layers=3, batch_first=True, dropout=0.3)
  (fc_layers): ModuleList(
    (0): Linear(in_features=192, out_features=96, bias=True)
    (1): Linear(in_features=96, out_features=48, bias=True)
    (2): Linear(in_features=48, out_features=1, bias=True)
  )
  (batch_norms): ModuleList(
    (0): BatchNorm1d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(48, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (dropout): Dropout(p=0.3, inplace=False)
  (relu): ReLU()
)

In [14]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

torch.Size([169711, 5, 50])
torch.Size([11384, 5, 50])
torch.Size([11567, 5, 50])

In [15]:
test = pd.read_csv(data_path + '/test_data.csv')

In [16]:
predictions = model(X_test).detach().numpy()
print(predictions.shape)
print(y_test.shape)

(11567, 1)
torch.Size([11567, 1])

In [17]:
print(torch.mean(y_test))
print(torch.var(y_test))

tensor(2.7053)
tensor(8.3782)

In [18]:
print(np.mean(predictions))
print(np.var(predictions))

2.523737
1.6563535

In [19]:
from sklearn.metrics import root_mean_squared_error, mean_absolute_error

rmse = root_mean_squared_error(y_test, predictions)
print(f"RMSE: {rmse}")

mae = mean_absolute_error(y_test, predictions)
print(f"MAE: {mae}")

RMSE: 2.653160810470581
MAE: 1.7770276069641113

In [20]:
X_test.shape

torch.Size([11567, 5, 50])

In [21]:
salah_y_test[16]

tensor([21.])

In [22]:
remaining_lagged_features = sorted(pickle.load(open(data_path + '/remaining_lagged_features.pkl', 'rb')))
remaining_lagged_features

['lagged_fixture_difficulty',
 'lagged_was_home',
 'last_1_assists',
 'last_1_bonus',
 'last_1_clean_sheets',
 'last_1_creativity',
 'last_1_goals_conceded',
 'last_1_goals_scored',
 'last_1_ict_index',
 'last_1_influence',
 'last_1_minutes',
 'last_1_red_cards',
 'last_1_result_encoded',
 'last_1_threat',
 'last_1_yellow_cards',
 'last_3_assists',
 'last_3_bonus',
 'last_3_clean_sheets',
 'last_3_creativity',
 'last_3_goals_conceded',
 'last_3_goals_scored',
 'last_3_ict_index',
 'last_3_influence',
 'last_3_minutes',
 'last_3_red_cards',
 'last_3_result_encoded',
 'last_3_threat',
 'last_3_yellow_cards',
 'last_5_assists',
 'last_5_bonus',
 'last_5_clean_sheets',
 'last_5_goals_conceded',
 'last_5_goals_scored',
 'last_5_influence',
 'last_5_red_cards',
 'last_5_result_encoded',
 'last_5_yellow_cards',
 'last_all_assists',
 'last_all_bonus',
 'last_all_clean_sheets',
 'last_all_creativity',
 'last_all_goals_conceded',
 'last_all_goals_scored',
 'last_all_ict_index',
 'last_all_influence',
 'last_all_red_cards',
 'last_all_result_encoded',
 'last_all_threat',
 'last_all_yellow_cards',
 'position_encoded']

In [23]:
for i in range(0, len(remaining_lagged_features)):
    if salah_x_test[0, -1, i] != 0:
        print(f"Feature {remaining_lagged_features[i]} is not zero")
        print("Value is ", salah_x_test[0, -1, i])
        print()

Feature lagged_fixture_difficulty is not zero
Value is  tensor(0.4000)

Feature position_encoded is not zero
Value is  tensor(2.)

In [24]:
salah_y_test[16]

tensor([21.])

In [25]:
test = pd.read_csv(data_path + '/test_data.csv')
salah_df = test[test['name'] == 'mohamed_salah']
salah_df[['name', 'GW', 'total_points', 'last_1_assists', 'last_1_goals_scored', 'last_1_ict_index']]

                name    GW  ...  last_1_goals_scored  last_1_ict_index
108    mohamed_salah   1.0  ...                 0.00          0.000000
420    mohamed_salah   2.0  ...                 0.25          0.424581
746    mohamed_salah   3.0  ...                 0.25          0.270950
1063   mohamed_salah   4.0  ...                 0.25          0.449721
1372   mohamed_salah   5.0  ...                 0.00          0.231844
1690   mohamed_salah   6.0  ...                 0.00          0.558659
1994   mohamed_salah   7.0  ...                 0.25          0.354749
2305   mohamed_salah   8.0  ...                 0.00          0.117318
2613   mohamed_salah   9.0  ...                 0.25          0.321229
2924   mohamed_salah  10.0  ...                 0.25          0.282123
3230   mohamed_salah  11.0  ...                 0.25          0.307263
3530   mohamed_salah  12.0  ...                 0.25          0.371508
3840   mohamed_salah  13.0  ...                 0.50          0.508380
4159   mohamed_salah  14.0  ...                 0.25          0.282123
4646   mohamed_salah  15.0  ...                 0.50          0.569832
4775   mohamed_salah  16.0  ...                 0.25          0.368715
5087   mohamed_salah  17.0  ...                 0.00          0.203911
5382   mohamed_salah  18.0  ...                 0.50          0.703911
5690   mohamed_salah  19.0  ...                 0.25          0.516760
5998   mohamed_salah  20.0  ...                 0.25          0.689944
6286   mohamed_salah  21.0  ...                 0.25          0.287709
6586   mohamed_salah  22.0  ...                 0.00          0.290503
6880   mohamed_salah  23.0  ...                 0.00          0.418994
7175   mohamed_salah  24.0  ...                 0.25          0.357542
7464   mohamed_salah  25.0  ...                 0.50          0.469274
7767   mohamed_salah  26.0  ...                 0.25          0.212291
8058   mohamed_salah  27.0  ...                 0.25          0.407821
8356   mohamed_salah  28.0  ...                 0.00          0.335196
8558   mohamed_salah  29.0  ...                 0.50          0.614525
8965   mohamed_salah  30.0  ...                 0.25          0.321229
9260   mohamed_salah  31.0  ...                 0.00          0.178771
9574   mohamed_salah  32.0  ...                 0.00          0.128492
9871   mohamed_salah  33.0  ...                 0.00          0.203911
10211  mohamed_salah  34.0  ...                 0.00          0.243017
10481  mohamed_salah  35.0  ...                 0.25          0.407821
10780  mohamed_salah  36.0  ...                 0.00          0.139665
11082  mohamed_salah  37.0  ...                 0.00          0.150838
11387  mohamed_salah  38.0  ...                 0.00          0.282123

[38 rows x 6 columns]

In [26]:
for i in range(0, len(salah_x_test)):
    input_to_game = salah_x_test[i].unsqueeze(0)
    print(f"Gameweek {i + 1}:")
    print("prediction", model(input_to_game).detach().numpy())
    print("actual", salah_y_test[i].item())

Gameweek 1:
prediction [[1.8993582]]
actual 14.0
Gameweek 2:
prediction [[2.9315047]]
actual 10.0
Gameweek 3:
prediction [[1.7797937]]
actual 17.0
Gameweek 4:
prediction [[3.5211277]]
actual 2.0
Gameweek 5:
prediction [[1.8468727]]
actual 6.0
Gameweek 6:
prediction [[5.99321]]
actual 10.0
Gameweek 7:
prediction [[3.109477]]
actual 3.0
Gameweek 8:
prediction [[8.208706]]
actual 12.0
Gameweek 9:
prediction [[6.0942206]]
actual 10.0
Gameweek 10:
prediction [[3.4518094]]
actual 9.0
Gameweek 11:
prediction [[11.98949]]
actual 14.0
Gameweek 12:
prediction [[9.7872505]]
actual 13.0
Gameweek 13:
prediction [[8.236986]]
actual 13.0
Gameweek 14:
prediction [[4.9975295]]
actual 18.0
Gameweek 15:
prediction [[9.719911]]
actual 13.0
Gameweek 16:
prediction [[3.811726]]
actual 5.0
Gameweek 17:
prediction [[12.107942]]
actual 21.0
Gameweek 18:
prediction [[6.5505466]]
actual 9.0
Gameweek 19:
prediction [[9.246908]]
actual 16.0
Gameweek 20:
prediction [[6.8241835]]
actual 7.0
Gameweek 21:
prediction [[11.224737]]
actual 2.0
Gameweek 22:
prediction [[4.527872]]
actual 3.0
Gameweek 23:
prediction [[7.29263]]
actual 8.0
Gameweek 24:
prediction [[6.2951546]]
actual 16.0
Gameweek 25:
prediction [[5.0814967]]
actual 8.0
Gameweek 26:
prediction [[6.9270105]]
actual 14.0
Gameweek 27:
prediction [[5.3050747]]
actual 6.0
Gameweek 28:
prediction [[3.261613]]
actual 15.0
Gameweek 29:
prediction [[3.486752]]
actual 12.0
Gameweek 30:
prediction [[6.801484]]
actual 3.0
Gameweek 31:
prediction [[4.077832]]
actual 2.0
Gameweek 32:
prediction [[6.442585]]
actual 6.0
Gameweek 33:
prediction [[6.6391025]]
actual 3.0
Gameweek 34:
prediction [[5.2609167]]
actual 8.0
Gameweek 35:
prediction [[6.8838687]]
actual 2.0
Gameweek 36:
prediction [[8.281913]]
actual 2.0
Gameweek 37:
prediction [[5.2956038]]
actual 2.0
Gameweek 38:
prediction [[6.8860426]]
actual 10.0

In [27]:
scores, total_score = get_season_performance(
    y_test=y_test,
    predictions=predictions,
    remaining_lagged_features=remaining_lagged_features
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
0.0 :  daniel_bentley
1.0 :  luke_thomas
2.0 :  matheus_franca_de_oliveira
3.0 :  daniel_jebbison
Bench players: ['daniel_bentley', 'luke_thomas', 'matheus_franca_de_oliveira', 'daniel_jebbison']
Bench cost: 167
length available players df 562
Available cash: 833
Decision variables: [aaron_cresswell, aaron_ramsdale, aaron_wan_bissaka, abdoulaye_doucoure, abdukodir_khusanov, abdul_fatawu, adam_armstrong, adam_lallana, adam_smith, adam_webster, adam_wharton, adama_traore, albert_gronbaek, alejandro_garnacho, alex_iwobi, alex_mccarthy, alex_moreno_lopera, alex_palmer, alex_scott, alexander_isak, alexis_mac_allister, alfie_dorrington, alfie_pond, ali_al_hamadi, alisson_ramses_becker, alphonse_areola, altay_bayindir, amad_diallo, amadou_onana, andre_onana, andre_trindade_da_costa_neto, andreas_hoelgebaum_pereira, andres_garcia, andrew_robertson, andy_irving, anthony_elanga, anthony_gordon, antoine_semenyo, antonee_robinson, antonin_kinsky, antony_matheus_dos_santos, archie_gray, arijanet_muric, armando_broja, armel_bella_kotchap, asher_agbinone, ashley_young, axel_disasi, axel_tuanzebe, ayden_heaven, bart_verbruggen, ben_brereton_diaz, ben_chilwell, ben_davies, ben_godfrey, ben_johnson, ben_mee, ben_winterburn, benjamin_white, benoit_badiashile, bernardo_veiga_de_carvalho_e_silva, bernd_leno, bilal_el_khannouss, billy_gilmour, bobby_de_cordova_reid, boubacar_kamara, boubacar_traore, boubakary_soumare, brajan_gruda, brandon_austin, brennan_johnson, bruno_borges_fernandes, bruno_guimaraes_rodriguez_moura, bryan_mbeumo, bukayo_saka, caleb_kporha, caleb_okoli, callum_hudson_odoi, callum_wilson, calvin_bassey, cameron_archer, cameron_burgess, caoimhin_kelleher, carlos_alcaraz_duran, carlos_baleba, carlos_henrique_casimiro, carlos_roberto_forbs_borges, carlos_soler, carlos_vinicius_alves_morais, chadi_riad_dnanou, charlie_taylor, cheick_doucoure, chido_obi_martin, chiedozie_ogbene, chris_richards, chris_wood, christian_eriksen, christian_norgaard, christian_walton, christopher_nkunku, claudio_echeverri, cody_gakpo, cole_palmer, conor_bradley, conor_chaplin, conor_coady, conor_townsend, craig_dawson, cristian_romero, crysencio_summerville, curtis_jones, daichi_kamada, dan_burn, dane_scarlett, dango_ouattara, daniel_bentley, daniel_castelo_podence, daniel_jebbison, daniel_munoz, danilo_dos_santos_de_oliveira, danny_ings, danny_ward, danny_welbeck, dara_o'shea, darwin_nunez_ribeiro, david_brooks, david_raya_martin, dean_henderson, dean_huijsen, declan_rice, dejan_kulusevski, destiny_udogie, diego_carlos_santos_silva, diego_gomez, diogo_dalot_teixeira, diogo_teixeira_da_silva, divin_mubama, djed_spence, dominic_calvert_lewin, dominic_solanke_mitchell, dominik_szoboszlai, donyell_malen, dwight_mcneil, eberechi_eze, eddie_nketiah, ederson_santana_de_moraes, edson_alvarez_velazquez, eiran_cashin, elliot_anderson, emerson_palmieri_dos_santos, emil_krafth, emile_smith_rowe, emiliano_buendia_stati, emiliano_martinez_romero, emmanuel_agbadou, endo_wataru, enes_unal, enzo_fernandez, eric_da_silva_moreira, erling_haaland, ethan_nwaneri, ethan_pinnock, evan_ferguson, ezri_konsa_ngoyo, fabian_schar, fabio_freitas_gouveia_carvalho, facundo_buonanotte, federico_chiesa, felipe_rodrigues_da_silva, ferdi_kadioglu, filip_jorgensen, flynn_downes, francisco_evanilson_de_lima_barbosa, francisco_jorge_tomas_oliveira, frank_onyeka, fraser_forster, gabriel_dos_santos_magalhaes, gabriel_fernando_de_jesus, gabriel_martinelli_silva, george_edmundson, george_hirst, georginio_rutter, goncalo_manuel_ganchinho_guedes, guglielmo_vicario, guido_rodriguez, gustavo_nunes_fernandes_gomes, hakon_valdimarsson, hamza_choudhury, harrison_armstrong, harrison_reed, harry_amass, harry_clarke, harry_howell, harry_maguire, harry_toffolo, harry_wilson, harry_winks, harvey_barnes, harvey_elliott, hwang_hee_chan, ian_maatsen, ibrahim_sangare, ibrahima_konate, idrissa_gueye, igor_julio_dos_santos_de_paulo, igor_thiago_nascimento_rodrigues, iliman_ndiaye, ilkay_gundogan, illia_zabarnyi, ismaila_sarr, issa_diop, jack_clarke, jack_grealish, jack_harrison, jack_hinshelwood, jack_stephens, jack_taylor, jacob_greaves, jacob_murphy, jacob_ramsey, jaden_philogene, jadon_sancho, jahmai_simpson_pusey, jake_evans, jake_o'brien, jakub_kiwior, jakub_moder, jakub_stolarczyk, james_bree, james_garner, james_hill, james_justin, james_maddison, james_mcatee, james_milner, james_tarkowski, james_ward_prowse, jamie_vardy, jan_bednarek, jan_paul_van_hecke, jannik_vestergaard, jarell_quansah, jarrad_branthwaite, jarrod_bowen, jason_steele, jay_robinson, jay_stansfield, jayden_danns, jayden_meghoma, jean_clair_todibo, jean_philippe_mateta, jean_ricner_bellegarde, jefferson_lerma_solis, jeffrey_schlupp, jens_cajuste, jeremy_doku, jeremy_monga, jeremy_sarmiento_morante, jesper_lindstrom, jhon_duran, joachim_andersen, joachim_kayi_sanda, joao_felix_sequeira, joao_pedro_ferreira_silva, joao_pedro_junqueira_de_jesus, joao_victor_gomes_da_silva, joe_aribo, joe_gomez, joe_lumley, joe_willock, joel_veltman, joel_ward, joelinton_cassio_apolinario_de_lira, john_mcginn, john_stones, jonny_evans, jordan_ayew, jordan_pickford, jorge_cuenca_barreno, jorge_luiz_frello_filho, jorgen_strand_larsen, jose_malheiro_de_sa, josh_acheampong, josh_king, joshua_zirkzee, josko_gvardiol, julian_araujo_zuniga, julio_enciso, julio_soler, jurrien_timber, justin_devenny, justin_kluivert, kaelan_casey, kai_havertz, kalvin_phillips, kamaldeen_sulemana, kasey_mcateer, keane_lewis_potter, kenny_tete, kepa_arrizabalaga, kevin_danso, kevin_de_bruyne, kevin_schade, kieran_tierney, kieran_trippier, kiernan_dewsbury_hall, kim_ji_soo, kobbie_mainoo, konstantinos_mavropanos, konstantinos_tsimikas, kosta_nedeljkovic, kristoffer_ajer, kyle_walker, kyle_walker_peters, lamare_bogarde, leandro_trossard, leif_davis, leny_yoro, leon_bailey, lesley_ugochukwu, levi_colwill, lewis_cook, lewis_dunk, lewis_hall, lewis_miley, lewis_orford, liam_delap, lisandro_martinez, lloyd_kelly, lucas_bergvall, lucas_digne, lucas_tolentino_coelho_de_lima, luis_diaz, luis_guilherme_lira_dos_santos, luis_sinisterra, lukasz_fabianski, luke_shaw, luke_thomas, luke_woolfenden, mads_hermansen, mads_roerslev_rasmussen, malo_gusto, manuel_akanji, manuel_ugarte, marc_cucurella_saseta, marc_guehi, marc_guiu_paz, marco_asensio, marcos_senesi, marcus_myers_harness, marcus_rashford, marcus_tavernier, mario_lemina, mark_flekken, mark_travers, marshall_munetsi, martial_godo, martin_dubravka, martin_odegaard, mason_holgate, mason_mount, massimo_luongo, mateo_kovacic, mateus_goncalo_espanha_fernandes, mateus_mane, matheus_franca_de_oliveira, matheus_luiz_nunes, matheus_santos_carneiro_da_cunha, mathias_jensen, mathis_amougou, mathys_tel, mats_wieffer, matt_doherty, matt_o'riley, matt_targett, matthijs_de_ligt, matty_cash, matz_sels, max_aarons, max_kilman, maxence_lacroix, maxwel_cornet, michael_golding, michael_kayode, michael_keane, michail_antonio, micky_van_de_ven, miguel_almiron_rejala, mikel_merino, mikey_moore, mikkel_damsgaard, milos_kerkez, mitoma_kaoru, mohamed_salah, mohammed_kudus, moises_caicedo_corozo, morgan_gibbs_white, morgan_rogers, murillo_santiago_costa_dos_santos, mykhailo_mudryk, myles_lewis_skelly, nasser_djiga, nathan_ake, nathan_broadhead, nathan_butler_oyedeji, nathan_collins, nathan_patterson, nathan_wood_gordon, nathaniel_clyne, neco_williams, nelson_cabral_semedo, nick_pope, niclas_fullkrug, nico_gonzalez, nico_o'reilly, nicolas_dominguez, nicolas_jackson, nikola_milenkovic, noni_madueke, norberto_bercique_gomes_betuncal, norberto_murara_neto, noussair_mazraoui, odsonne_edouard, ola_aina, olabade_aluko, oleksandr_zinchenko, oliver_skipp, ollie_scarles, ollie_watkins, omar_marmoush, omari_giraud_hutchinson, orel_mangala, oscar_bobb, pablo_sarabia, pape_matar_sarr, paris_maghoma, patrick_dorgu, patson_daka, pau_torres, paul_onuachu, pedro_cardoso_de_lima, pedro_lomba_neto, pedro_porro, pervis_estupinan, phil_foden, philip_billing, radu_dragusin, raheem_sterling, ramon_sosa, rasmus_hojlund, raul_jimenez, rayan_ait_nouri, reece_james, reiss_nelson, remy_rees_dottin, renato_palma_veiga, ricardo_barbosa_pereira, riccardo_calafiori, richarlison_de_andrade, rico_henry, rico_lewis, robert_sanchez, robin_olsen, rodrigo_'rodri'_hernandez, rodrigo_bentancur, rodrigo_martins_gomes, rodrigo_muniz_carvalho, romain_esse, roman_dixon, romeo_lavia, ronnie_edwards, ross_barkley, ross_stewart, ruben_gato_alves_dias, ryan_christie, ryan_fraser, ryan_gravenberch, ryan_manning, ryan_sessegnon, ryan_trevitt, ryan_yates, sam_johnstone, sam_morsy, sam_szmodics, samuel_amo_ameyaw, samuel_edozie, sander_berge, sandro_tonali, santiago_bueno, sasa_lukic, savio_'savinho'_moreira_de_oliveira, scott_mctominay, seamus_coleman, sean_longstaff, sepp_van_den_berg, sergio_reguilon, shumaira_mheuka, simon_adingra, solly_march, son_heung_min, stefan_ortega_moreno, stephy_mavididi, sugawara_yukinari, sven_botman, taiwo_awoniyi, tariq_lamptey, taylor_harwood_bellis, thomas_partey, tim_iroegbunam, timo_werner, timothy_castagne, tino_livramento, toby_collyer, tom_cairney, tom_king, tomas_soucek, tomiyasu_takehiro, tommy_doyle, tosin_adarabioyo, toti_antonio_gomes, trent_alexander_arnold, trevoh_chalobah, tyler_adams, tyler_dibling, tyler_fredricson, tyrell_malacia, tyrick_mitchell, tyrique_george, tyrone_mings, victor_kristiansen, victor_lindelof, virgil_van_dijk, vitalii_mykolenko, vitaly_janelt, vitezslav_jaros, vitor_de_oliveira_nunes_dos_reis, vladimir_coufal, welington_damascena_santos, wes_burns, wesley_fofana, wilfred_ndidi, will_alves, will_hughes, will_lankshear, will_smallbone, william_osula, william_saliba, willian_borges_da_silva, willy_boly, wilson_odobert, wout_faes, woyo_coulibaly, yankuba_minteh, yasin_ayari, yehor_yarmoliuk, yerson_mosquera, yoane_wissa, youri_tielemans, youssef_ramalho_chermiti, yunus_emre_konak, yves_bissouma, zain_silcott_duberry]

In [28]:
scores

      GW  ... total_score
0    1.0  ...        33.0
1    2.0  ...        43.0
2    3.0  ...        33.0
3    4.0  ...        49.0
4    5.0  ...        26.0
5    6.0  ...        78.0
6    7.0  ...        73.0
7    8.0  ...        44.0
8    9.0  ...        85.0
9   10.0  ...        62.0
10  11.0  ...        65.0
11  12.0  ...        47.0
12  13.0  ...        67.0
13  14.0  ...        67.0
14  15.0  ...        70.0
15  16.0  ...        58.0
16  17.0  ...        80.0
17  18.0  ...        53.0
18  19.0  ...        72.0
19  20.0  ...        81.0
20  21.0  ...        42.0
21  22.0  ...        57.0
22  23.0  ...        81.0
23  24.0  ...        52.0
24  25.0  ...        34.0
25  26.0  ...        56.0
26  27.0  ...        53.0
27  28.0  ...        49.0
28  29.0  ...        48.0
29  30.0  ...        53.0
30  31.0  ...        17.0
31  32.0  ...        58.0
32  33.0  ...        33.0
33  34.0  ...        22.0
34  35.0  ...        32.0
35  36.0  ...        33.0
36  37.0  ...        38.0
37  38.0  ...        46.0

[38 rows x 4 columns]

In [29]:
total_score.item()

1990.0

In [30]:
scores, total_score = season_performance_with_unlimited_transfers(
    y_test=y_test,
    predictions=predictions,
    remaining_lagged_features=remaining_lagged_features
)

Players with NaN total_points_last_season: []
Number of NaN values remaining: 0
0.0 :  daniel_bentley
1.0 :  luke_thomas
2.0 :  matheus_franca_de_oliveira
3.0 :  daniel_jebbison
Bench players: ['daniel_bentley', 'luke_thomas', 'matheus_franca_de_oliveira', 'daniel_jebbison']
Bench cost: 167
Simulating season with unlimited transfers for 38 gameweeks
Available budget per gameweek: 833

--- Gameweek 1.0 ---
Players available for GW 1.0: 316
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/1002ec9fff1142228349fba6604e51fb-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/1002ec9fff1142228349fba6604e51fb-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1927 RHS
At line 1953 BOUNDS
At line 2270 ENDATA
Problem MODEL has 25 rows, 316 columns and 948 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 21.7011 - 0.00 seconds
Cgl0004I processed model has 25 rows, 176 columns (176 integer (106 of which binary)) and 528 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -21.7011
Cbc0038I Cleaned solution of -21.7011
Cbc0038I Before mini branch and bound, 176 integers at bound fixed and 0 continuous of which 2 were internal integer and 0 internal continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -21.7011 - took 0.00 seconds
Cbc0012I Integer solution of -21.701145 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -21.701145410538, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -21.7011 to -21.7011
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                21.70114541
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                          name  actual  predicted
1080             ollie_watkins     2.0   1.881464
1513  dominic_solanke_mitchell     2.0   1.881464
4970          christian_walton     2.0   2.116714
5558   diogo_teixeira_da_silva     8.0   1.899358
5777                 luis_diaz     3.0   1.899358
6356                rico_lewis     6.0   1.973268
8427         rodrigo_bentancur     1.0   1.899358
8548               archie_gray     1.0   1.899358
9378           rayan_ait_nouri     1.0   2.083601
9487              craig_dawson     1.0   2.083601
9689           yerson_mosquera     1.0   2.083601
GW 1.0 optimal team: ['archie_gray', 'christian_walton', 'craig_dawson', 'diogo_teixeira_da_silva', 'dominic_solanke_mitchell', 'luis_diaz', 'ollie_watkins', 'rayan_ait_nouri', 'rico_lewis', 'rodrigo_bentancur', 'yerson_mosquera']
GW 1.0 score: 36.0
Team cost: 635

--- Gameweek 2.0 ---
Players available for GW 2.0: 319
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/f9e5187710c2489db1741266290d2c33-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/f9e5187710c2489db1741266290d2c33-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1945 RHS
At line 1971 BOUNDS
At line 2291 ENDATA
Problem MODEL has 25 rows, 319 columns and 957 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 31.3565 - 0.00 seconds
Cgl0004I processed model has 25 rows, 318 columns (318 integer (317 of which binary)) and 954 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -31.3565
Cbc0038I Cleaned solution of -31.3565
Cbc0038I Before mini branch and bound, 318 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -31.3565 - took 0.00 seconds
Cbc0012I Integer solution of -31.356453 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -31.356452941893, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -31.3565 to -31.3565
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                31.35645294
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.01

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                    name  actual  predicted
46                           kai_havertz     2.0   2.912761
364                          bukayo_saka     6.0   3.101370
2495                        joel_veltman     2.0   2.399265
2566                       danny_welbeck     9.0   2.944005
4365                          bernd_leno     3.0   2.244010
5458              trent_alexander_arnold     6.0   2.656533
5933                  dominik_szoboszlai     2.0   3.741007
6018                     virgil_van_dijk     7.0   2.331947
6091  bernardo_veiga_de_carvalho_e_silva     2.0   3.468668
8642                      james_maddison     6.0   2.983642
8673                         pedro_porro     6.0   2.573244
GW 2.0 optimal team: ['bernardo_veiga_de_carvalho_e_silva', 'bernd_leno', 'bukayo_saka', 'danny_welbeck', 'dominik_szoboszlai', 'james_maddison', 'joel_veltman', 'kai_havertz', 'pedro_porro', 'trent_alexander_arnold', 'virgil_van_dijk']
GW 2.0 score: 60.0
Team cost: 720

--- Gameweek 3.0 ---
Players available for GW 3.0: 312
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/6fe58edac1b74290b4753316f716c41a-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/6fe58edac1b74290b4753316f716c41a-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1903 RHS
At line 1929 BOUNDS
At line 2242 ENDATA
Problem MODEL has 25 rows, 312 columns and 936 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 44.7558 - 0.00 seconds
Cgl0004I processed model has 25 rows, 310 columns (310 integer (308 of which binary)) and 930 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -44.7558
Cbc0038I Cleaned solution of -44.7558
Cbc0038I Before mini branch and bound, 310 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -44.7558 - took 0.00 seconds
Cbc0012I Integer solution of -44.755812 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -44.755811691284, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -44.7558 to -44.7558
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                44.75581169
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                name  actual  predicted
365                      bukayo_saka     6.0   5.968986
1636                  nathan_collins     5.0   3.924519
1712                    mark_flekken     3.0   7.085848
1942                   ethan_pinnock     1.0   4.303907
3038                     cole_palmer     6.0   4.762030
4767                   jacob_greaves     2.0   4.127460
5354                     jamie_vardy     1.0   2.005827
7223                  alexander_isak     9.0   2.803892
7881                   neco_williams     2.0   3.046425
8807                   son_heung_min     3.0   3.096747
9255  lucas_tolentino_coelho_de_lima     2.0   3.630171
GW 3.0 optimal team: ['alexander_isak', 'bukayo_saka', 'cole_palmer', 'ethan_pinnock', 'jacob_greaves', 'jamie_vardy', 'lucas_tolentino_coelho_de_lima', 'mark_flekken', 'nathan_collins', 'neco_williams', 'son_heung_min']
GW 3.0 score: 49.0
Team cost: 725

--- Gameweek 4.0 ---
Players available for GW 4.0: 315
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/e1567e96f96248df803538926897e1e4-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/e1567e96f96248df803538926897e1e4-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1921 RHS
At line 1947 BOUNDS
At line 2263 ENDATA
Problem MODEL has 25 rows, 315 columns and 945 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 56.584 - 0.00 seconds
Cgl0004I processed model has 25 rows, 313 columns (313 integer (311 of which binary)) and 939 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -56.584
Cbc0038I Cleaned solution of -56.584
Cbc0038I Before mini branch and bound, 313 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -56.584 - took 0.00 seconds
Cbc0012I Integer solution of -56.583994 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -56.58399438858, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -56.584 to -56.584
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                56.58399439
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                        name  actual  predicted
722              lucas_digne     4.0   4.650259
1425         antoine_semenyo     1.0   7.881720
2463      jan_paul_van_hecke     6.0   3.851584
2982         nicolas_jackson     1.0   3.378492
3312            eberechi_eze     2.0   8.682220
4012            amadou_onana     1.0   4.096615
5432   alisson_ramses_becker     2.0   4.620984
5460  trent_alexander_arnold     1.0   4.987908
5749         ibrahima_konate     2.0   5.091191
6129         kevin_de_bruyne     2.0   4.467912
6297          erling_haaland    13.0   4.875108
GW 4.0 optimal team: ['alisson_ramses_becker', 'amadou_onana', 'antoine_semenyo', 'eberechi_eze', 'erling_haaland', 'ibrahima_konate', 'jan_paul_van_hecke', 'kevin_de_bruyne', 'lucas_digne', 'nicolas_jackson', 'trent_alexander_arnold']
GW 4.0 score: 48.0
Team cost: 760

--- Gameweek 5.0 ---
Players available for GW 5.0: 312
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019

command line - /opt/anaconda3/envs/fpl_helper/lib/python3.11/site-packages/pulp/apis/../solverdir/cbc/osx/i64/cbc /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/05b6952460c145adb406d371c4c35319-pulp.mps -max -timeMode elapsed -branch -printingOptions all -solution /var/folders/yv/683h12gj4mdc5txzm0lh6j0h0000gn/T/05b6952460c145adb406d371c4c35319-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 30 COLUMNS
At line 1903 RHS
At line 1929 BOUNDS
At line 2242 ENDATA
Problem MODEL has 25 rows, 312 columns and 936 elements
Coin0008I MODEL read with 0 errors
Option for timeMode changed from cpu to elapsed
Continuous objective value is 57.9852 - 0.00 seconds
Cgl0004I processed model has 25 rows, 311 columns (311 integer (310 of which binary)) and 933 elements
Cbc0038I Initial state - 0 integers unsatisfied sum - 0
Cbc0038I Solution found of -57.9852
Cbc0038I Cleaned solution of -57.9852
Cbc0038I Before mini branch and bound, 311 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (0.00 seconds)
Cbc0038I After 0.00 seconds - Feasibility pump exiting with objective of -57.9852 - took 0.00 seconds
Cbc0012I Integer solution of -57.985183 found by feasibility pump after 0 iterations and 0 nodes (0.00 seconds)
Cbc0001I Search completed - best objective -57.985183238982, took 0 iterations and 0 nodes (0.00 seconds)
Cbc0035I Maximum depth 0, 0 variables fixed on reduced cost
Cuts at root node changed objective from -57.9852 to -57.9852
Probing was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Gomory was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Knapsack was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
Clique was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
MixedIntegerRounding2 was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
FlowCover was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
TwoMirCuts was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)
ZeroHalf was tried 0 times and created 0 cuts of which 0 were active after adding rounds of cuts (0.000 seconds)

Result - Optimal solution found

Objective value:                57.98518324
Enumerated nodes:               0
Total iterations:               0
Time (CPU seconds):             0.00
Time (Wallclock seconds):       0.00

Option for printingOptions changed from normal to all
Total time (CPU seconds):       0.01   (Wallclock seconds):       0.01

                                     name  actual  predicted
49                            kai_havertz     2.0   3.262464
367                           bukayo_saka     4.0   4.669253
3181                        wesley_fofana     0.0   6.230773
3924                        dwight_mcneil     2.0   5.682717
4698                           leif_davis     2.0   7.701284
4952                        axel_tuanzebe     2.0   7.583565
5781                            luis_diaz    16.0   5.286417
5903                     andrew_robertson     6.0   5.918737
6856                          andre_onana     9.0   4.236202
7294  joelinton_cassio_apolinario_de_lira     2.0   3.926045
7973                           chris_wood     8.0   3.487725
GW 5.0 optimal team: ['andre_onana', 'andrew_robertson', 'axel_tuanzebe', 'bukayo_saka', 'chris_wood', 'dwight_mcneil', 'joelinton_cassio_apolinario_de_lira', 'kai_havertz', 'leif_davis', 'luis_diaz', 'wesley_fofana']
GW 5.0 score: 69.0
Team cost: 670

--- Gameweek 6.0 ---
Players available for GW 6.0: 310
Welcome to the CBC MILP Solver
Version: 2.10.3
Build Date: Dec 15 2019


In [31]:
total_score.item()

3260.0

In [32]:
scores

                                                 team  gw_score
0   [archie_gray, christian_walton, craig_dawson, ...      36.0
1   [bernardo_veiga_de_carvalho_e_silva, bernd_len...      60.0
2   [alexander_isak, bukayo_saka, cole_palmer, eth...      49.0
3   [alisson_ramses_becker, amadou_onana, antoine_...      48.0
4   [andre_onana, andrew_robertson, axel_tuanzebe,...      69.0
5   [cole_palmer, dejan_kulusevski, dwight_mcneil,...     120.0
6   [bryan_mbeumo, bukayo_saka, chris_wood, danny_...     119.0
7   [danny_welbeck, dwight_mcneil, jadon_sancho, j...     104.0
8   [bryan_mbeumo, bukayo_saka, chris_wood, cole_p...      97.0
9   [alex_moreno_lopera, antoine_semenyo, brennan_...     100.0
10  [bernd_leno, bruno_borges_fernandes, calvin_ba...     110.0
11  [aaron_wan_bissaka, bukayo_saka, james_maddiso...     134.0
12  [bukayo_saka, chris_wood, cole_palmer, gabriel...     147.0
13  [alex_iwobi, alexander_isak, ashley_young, erl...     115.0
14  [aaron_wan_bissaka, alexander_isak, bryan_mbeu...     115.0
15  [amad_diallo, bryan_mbeumo, erling_haaland, fa...     115.0
16  [alexander_isak, antoine_semenyo, fabian_schar...     138.0
17  [amadou_onana, anthony_gordon, cody_gakpo, col...     102.0
18  [alexander_isak, chris_wood, lewis_hall, moham...     135.0
19  [bryan_mbeumo, chris_richards, cole_palmer, da...     114.0
20  [alexander_isak, amad_diallo, antoine_semenyo,...     117.0
21  [bruno_borges_fernandes, cody_gakpo, cole_palm...      89.0
22  [amad_diallo, antoine_semenyo, ben_mee, dango_...      92.0
23  [ben_davies, caleb_okoli, cole_palmer, dejan_k...      92.0
24  [alexander_isak, antoine_semenyo, axel_tuanzeb...      68.0
25  [alexander_isak, bryan_mbeumo, dango_ouattara,...      87.0
26  [chris_wood, cole_palmer, djed_spence, ederson...      81.0
27  [bruno_borges_fernandes, bryan_mbeumo, cole_pa...      50.0
28  [abdoulaye_doucoure, andreas_hoelgebaum_pereir...      62.0
29  [ben_johnson, bernd_leno, bukayo_saka, jan_pau...      55.0
30  [andrew_robertson, bryan_mbeumo, bukayo_saka, ...      51.0
31  [alex_scott, alexander_isak, andrew_robertson,...      54.0
32  [aaron_ramsdale, brennan_johnson, dango_ouatta...      55.0
33  [brennan_johnson, bruno_borges_fernandes, dean...      76.0
34  [adama_traore, alejandro_garnacho, conor_coady...      61.0
35  [bruno_borges_fernandes, david_raya_martin, em...      45.0
36  [adam_webster, anthony_gordon, antonin_kinsky,...      39.0
37  [antoine_semenyo, chris_wood, conor_coady, dan...      59.0